### ISSUE TITLE
Sorting repositories by priority is wrong for `default` entries in GTK UI

### ISSUE THREAD

**Issue by rindeal** [yast/yast-packager#517]
On Leap 15.1, the sorting works fine, on Tumbleweed it looks like this:

![Screenshot_20200331_211815](https://user-images.githubusercontent.com/5360877/78066503-96236200-7384-11ea-92a8-54949a088c93.png)

TUI works fine, it's just the GTK UI.

**Comment by ancorgs** [comment]
This is also reported at bugzilla here: https://bugzilla.suse.com/show_bug.cgi?id=1178004

To avoid duplication, I'm going to close this github issue since bugzilla is the main tracking platform for core YaST modules.
