### ISSUE TITLE
Add multiple selection of packages

### ISSUE THREAD

**Issue by rominf** [yast/yast-packager#86]
Use case: I have Qt development packages installed and I want freeze them. It took 4 minutes to press `*`, then `↓` to freeze all packages. It would be much easier to select them all and then press `*`.

**Comment by lslezak** [comment]
You can use filtering to change multiple packages:

- Switch to the *Search* tab
- Enter the needed filter, e.g. `libqt`
- Right click in the list of packages, select the required action (e.g. *Protect*) in the *All in this list* submenu
- You can manually fine tune the changes, revert some changes, add more etc...

![all_in_this_list](https://cloud.githubusercontent.com/assets/907998/14980429/dda3b80e-1128-11e6-9036-af886cbef4a8.png)

**Comment by rominf** [comment]
Thank you for detailed explanation, @lslezak!
